# -*- coding: utf-8 -*-
"""random_pw_generaor.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vkBH_mseJCadpaLlxsP402qaUkFe67Qc
"""

import random
num=[0,1,2,3,4,5,6,7,8,9]
sym=['!','@','#','$','%','&','|']
schar=['a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z']
cchar=['A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z']
s=[]
s.append(random.choice(cchar))
s.append(random.choice(schar))
s.append(random.choice(schar))
s.append(random.choice(schar))
s.append(random.choice(schar))
s.append(random.choice(schar))
s.append(random.choice(sym))
s.append(random.choice(num))
s1=''.join(map(str,s))
print(s1)